### ISSUE TITLE
Model Size?

### ISSUE THREAD

**Issue by Shiran-Yuan** [cyw-3d/SAR3D#1]
Hi! Thank you for the awesome work! Just a quick question out of curiosity: how many parameters are in your encoder and 3d generation model respectively? Thanks!

**Comment by cyw-3d** [comment]
Hi! Thanks for your kind words! Our VQVAE has 0.18 billion parameters, text-condition generation model has 0.38 billlion parameters and image-condition generation model has 1.2 billion parameters.

**Comment by Shiran-Yuan** [comment]
Thank you! In addition, it seems that the paper did not specify which dataset was chosen for benchmarking. May I know how the benchmarking was conducted?

**Comment by cyw-3d** [comment]
Thank you for your question. We use 600 objects from G-objaverse for benchmarking, and we will add these details in the following version.
